##
##  Travis CI config for LibreSignage.
##

language: php
php:
	- '7.2'

sudo: required

services:
	- docker

before_install:
	apt-get update
	
install:
	# Install dependencies
	apt-get install pandoc ruby-sass
	npm install

script:
	# Build the Docker image.
	./build/helpers/docker/build_img.sh
