##
##  Travis CI config for LibreSignage.
##

language: php
php:
    - '7.2'

sudo: required

branches:
    only:
        - master
        - next
        - feature/travis
        - /v[0-9]+.[0-9]+.x/
        - /v[0-9]+.[0-9]+.[0-9]+-dev/

services:
    - docker

before_install:
    - sudo apt-get update

install:
    # Install dependencies
    - sudo apt-get install pandoc ruby-sass
    - npm install

script:
    # Build the Docker image.
    - ./build/helpers/docker/build_img.sh
