##
##  Travis CI config for LibreSignage.
##

# Use Ubuntu Xenial. This is mainly because compiling
# LibreSignage needs a newer version of GNU make that
# doesn't exist on Trusty.
dist: xenial

language: php
php:
    - '7.2'

services:
    - docker

sudo: required

branches:
    only:
        - master
        - next
        - feature/travis
        - /v[0-9]+.[0-9]+.x/
        - /v[0-9]+.[0-9]+.[0-9]+-dev/


before_install:
    - sudo apt-get update

install:
    # Install dependencies
    - sudo apt-get install pandoc ruby-sass
    - npm install

script:
    # Build the Docker image.
    - ./build/helpers/docker/build_img.sh
